#!/usr/bin/ruby

require 'erb'
class Foo
    attr_accessor :PLACEHOLDER_NAME,
:PLACEHOLDER_DIRECTOR_UUID,
:PLACEHOLDER_ACCESS_KEY_ID,
:PLACEHOLDER_SECRET_KEY,
:PLACEHOLDER_SUBNET_FOR_AZ1,
:PLACEHOLDER_SUBNET_FOR_AZ2,
:PLACEHOLDER_DOMAIN,
:PLACEHOLDER_UAA_CERT,
:PLACEHOLDER_NATS_USER,
:PLACEHOLDER_NATS_PASSWORD,
:PLACEHOLDER_CC_DB_ENCRYPTION_KEY,
:PLACEHOLDER_BULK_API_PASSWORD,
:PLACEHOLDER_STAGING_UPLOAD_PASSWORD,
:PLACEHOLDER_STAGING_UPLOAD_USER,
:PLACEHOLDER_UAA_ADMIN_CLIENT_SECRET,
:PLACEHOLDER_UAA_JWT_SIGNING_KEY,  # Use the YAML "|" character to format multiline RSA key data
:PLACEHOLDER_UAA_JWT_VERIFICATION_KEY, # Use the YAML "|" character to format multiline RSA key data
:PLACEHOLDER_UAA_CLIENTS_LOGIN_SECRET,
:PLACEHOLDER_UAA_CLIENTS_DEVELOPER_CONSOLE_SECRET,
:PLACEHOLDER_UAA_CLIENTS_APP_DIRECT_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SUPPORT_SERVICES_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SERVICESMGMT_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SPACE_MAIL_SECRET,
:PLACEHOLDER_UAA_CLIENTS_NOTIFICATION_SECRET,
:PLACEHOLDER_UAA_BATCH_USERNAME,
:PLACEHOLDER_UAA_BATCH_PASSWORD,
:PLACEHOLDER_UAA_CC_CLIENT_SECRET,
:PLACEHOLDER_UAADB_PROPERTIES,
:PLACEHOLDER_CCDB_PROPERTIES,
:PLACEHOLDER_ROUTER_STATUS_USER,
:PLACEHOLDER_ROUTER_STATUS_PASSWORD,
:PLACEHOLDER_LOGGREGATOR_SECRET
      def template_binding
            binding
              end
end

=begin
:PLACEHOLDER_NAME,
:PLACEHOLDER_DIRECTOR_UUID,
:PLACEHOLDER_ACCESS_KEY_ID,
:PLACEHOLDER_SECRET_KEY,
:PLACEHOLDER_SUBNET_FOR_AZ1,
:PLACEHOLDER_SUBNET_FOR_AZ2,
:PLACEHOLDER_DOMAIN,
:PLACEHOLDER_UAA_CERT,
:PLACEHOLDER_NATS_USER,
:PLACEHOLDER_NATS_PASSWORD,
:PLACEHOLDER_CC_DB_ENCRYPTION_KEY,
:PLACEHOLDER_BULK_API_PASSWORD,
:PLACEHOLDER_STAGING_UPLOAD_PASSWORD,
:PLACEHOLDER_STAGING_UPLOAD_USER,
:PLACEHOLDER_UAA_ADMIN_CLIENT_SECRET,
:PLACEHOLDER_UAA_JWT_SIGNING_KEY,  # Use the YAML "|" character to format multiline RSA key data
:PLACEHOLDER_UAA_JWT_VERIFICATION_KEY, # Use the YAML "|" character to format multiline RSA key data
:PLACEHOLDER_UAA_CLIENTS_LOGIN_SECRET,
:PLACEHOLDER_UAA_CLIENTS_DEVELOPER_CONSOLE_SECRET,
:PLACEHOLDER_UAA_CLIENTS_APP_DIRECT_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SUPPORT_SERVICES_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SERVICESMGMT_SECRET,
:PLACEHOLDER_UAA_CLIENTS_SPACE_MAIL_SECRET,
:PLACEHOLDER_UAA_CLIENTS_NOTIFICATION_SECRET,
:PLACEHOLDER_UAA_BATCH_USERNAME,
:PLACEHOLDER_UAA_BATCH_PASSWORD,
:PLACEHOLDER_UAA_CC_CLIENT_SECRET,
:PLACEHOLDER_UAADB_PROPERTIES,
:PLACEHOLDER_CCDB_PROPERTIES,
:PLACEHOLDER_ROUTER_STATUS_USER,
:PLACEHOLDER_ROUTER_STATUS_PASSWORD,
:PLACEHOLDER_LOGGREGATOR_SECRET
=end




new_file = File.open("./result.txt", "w+")
template = File.read("./template.erb")
foo = Foo.new
foo.PLACEHOLDER_NATS_PASSWORD = "Hello"
new_file << ERB.new(template).result(foo.template_binding)
new_file.close
